#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/lenovo/TB375FC

# MT6897 common trees from mt6897-devs/lineage-23.2:
# mssi.mk (RRO for telephony/wifi config), mediatek-frameworks.mk (adds
# mediatek-common to PRODUCT_BOOT_JARS), compat.mk (telephony-common-stub
# LineageOS compat shim). The Soong namespace addition lets platform-bootclasspath
# resolve mediatek-common.
PRODUCT_SOONG_NAMESPACES += hardware/mediatek

# The official hardware/mediatek tree builds the memtrack/thermal/vibrator HALs
# and the perf/power client libs from source. TB375FC/TB373FU ship all of these
# as prebuilt vendor blobs, so opt out of the source builds (otherwise the source
# module and the prebuilt collide on the vendor partition). These flags are read
# by select() in hardware/mediatek/{aidl/*,libmtkperf_client}/Android.bp.
$(call soong_config_set,mediatek_hardware,use_prebuilt_memtrack,true)
$(call soong_config_set,mediatek_hardware,use_prebuilt_thermal,true)
$(call soong_config_set,mediatek_hardware,use_prebuilt_vibrator,true)
$(call soong_config_set,mediatek_hardware,use_prebuilt_perf,true)

$(call inherit-product, hardware/mediatek/overlay/mssi.mk)
$(call inherit-product, hardware/mediatek/frameworks/mediatek-frameworks.mk)
$(call inherit-product, hardware/lineage/compat/frameworks/compat.mk)

# mediatek-frameworks.mk (inherited above) adds `mediatek-common` to
# PRODUCT_BOOT_JARS, which Soong resolves to the LOS-source java_library at
# hardware/mediatek/frameworks/common/Android.bp -- a 1712-byte dex stub with
# no real classes. Stock Lenovo MTK apps (GeofenceService, MtkSettingsProvider,
# callrecorder etc.) ClassNotFound-crash at runtime because the real
# com.mediatek.common.* classes live in the 88 KB proprietary jar at
# /system_ext/framework/mediatek-common.jar, which isn't on BOOTCLASSPATH.
#
# Fix: a dex_import at device/lenovo/TB375FC/prebuilts/framework/Android.bp
# is declared with the SAME name (`mediatek-common`) as the LOS source and
# `prefer: true`. Soong's source-vs-prebuilt resolution picks the prebuilt;
# the LOS source becomes inactive (not built, not installed, not in boot
# classpath). PRODUCT_BOOT_JARS keeps referring to `mediatek-common` and now
# resolves to our 88 KB jar.
#
# (Kept in device tree because vendor/lenovo/TB375FC/Android.bp is auto-
# generated by gen_vendor_mk.py and would wipe a dex_import added there.)

# Enable Android's built-in freeform window manager for tablet multitasking.
# Apps launched via the taskbar (Launcher3 tablet UI) render in resizable,
# movable windows. Replaces the broken Smart Connect / Ready For desktop mode
# with LOS-native multitasking - no Lenovo vendor blobs needed.
#
# The property is read at boot by PackageManagerService.hasSystemFeature() to
# advertise FEATURE_FREEFORM_WINDOW_MANAGEMENT, and by WindowManager to allow
# freeform launch modes. Tablet form factor + this prop is what unlocks the
# "windowed apps on home screen" UX you see in modern Android tablet builds.
#
# persist.* framework props must land on /system/build.prop (read before
# PackageManagerService starts); PRODUCT_PROPERTY_OVERRIDES routes to
# /vendor/build.prop in AOSP A16, which is too late.
PRODUCT_SYSTEM_PROPERTIES += persist.wm.freeform_window_management=1

# Conditional Access System HAL (AIDL). Stock A16 PRC ships it. Used by digital-
# broadcast and a few streaming apps to request content protection keys. Most
# modern streaming uses Widevine (we have that), but adding CAS prevents
# potential edge-case binding failures for apps that bind ICas at startup.
# AOSP A16 packages CAS as a vendor APEX; the example binary itself is
# installable: false because it is built into the APEX. Reference the APEX
# (com.android.hardware.cas) so the binary + init.rc + vintf fragment ship
# together at /vendor/apex/com.android.hardware.cas.apex.
PRODUCT_PACKAGES += com.android.hardware.cas


# ro.boot.hardware=mt8792 but DT compatible is mediatek,MT6897, so stock ships
# both fstab.mt6897 and fstab.mt8792 (identical). Mirror that to cover both
# resolutions of fstab.${ro.hardware}.
#
# All Lenovo init.rc + fstab prebuilt_etc modules are auto-declared in
# rootdir/Android.bp and listed in tb375fc-rootdir-packages.mk.
include $(DEVICE_PATH)/tb375fc-rootdir-packages.mk

# tb375fc-vendor-symlinks.mk is NOT included here; its rules reference
# $(TARGET_OUT_VENDOR) which is unset during product-config. It is included
# from Android.mk instead, which runs after envsetup.mk.

# 367 vendor properties from stock vendor/build.prop (build.prop is generated,
# not blobbed). Includes Mali EGL config table, surfaceflinger phase offsets,
# MTK HAL knobs, Lenovo init triggers. Required for libGLES_mali eglInitialize.
include $(DEVICE_PATH)/tb375fc-stock-vendor-props.mk

# GApps (MindTheGapps): client ID, Setup Wizard fixes, Play Integrity props.
# System/product/system_ext partitions use ext4 (see BoardConfig.mk) for
# compatibility with the MindTheGapps recovery installer.
include $(DEVICE_PATH)/tb375fc-gapps.mk

# 144 Hz animation engine: HWUI, SurfaceFlinger frame-rate governance,
# ART parallel dex2oat on the big cluster, NT36532 high-frequency touch.
include $(DEVICE_PATH)/tb375fc-animations.mk


PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/rootdir/etc/fstab.mt6897:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/first_stage_ramdisk/fstab.mt6897 \
    $(DEVICE_PATH)/rootdir/etc/fstab.mt6897:$(TARGET_COPY_OUT_RECOVERY)/root/first_stage_ramdisk/fstab.mt6897 \
    $(DEVICE_PATH)/rootdir/etc/fstab.mt8792:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/first_stage_ramdisk/fstab.mt8792 \
    $(DEVICE_PATH)/rootdir/etc/fstab.mt8792:$(TARGET_COPY_OUT_RECOVERY)/root/first_stage_ramdisk/fstab.mt8792

# Game Manager Service feature declaration: Enables AOSP game modes and performance tuning APIs.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.software.game_service.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/android.software.game_service.xml

# Prebuilt apps default permission grants
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/configs/default-permissions-prebuilts.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/default-permissions/default-permissions-prebuilts.xml



# MTK SurfaceFlinger extension HAL framework manifest fragment (vendor libpowerhal
# calls AServiceManager_getService for IMtkSF_ext/default at init; without this
# declaration in the framework manifest the lookup returns NULL and libpowerhal
# crashes with SIGSEGV). Installed as a framework VINTF manifest fragment so
# assemble_vintf merges it with the rest of the system manifest at build time.
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/manifest/mtksf_ext-mtk-default.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/vintf/manifest/mtksf_ext-mtk-default.xml


# Novatek NT36532 touch IC firmware. In recovery /vendor never mounts, so
# the kernel firmware loader can't find these unless they're in vendor_ramdisk00
# at /vendor/firmware/. In normal boot the real /vendor mount masks the
# ramdisk copy. Cost: 4 x 240 KB.
PRODUCT_COPY_FILES += \
    vendor/lenovo/TB375FC/proprietary/vendor/firmware/novatek_ts_fw_tm.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/novatek_ts_fw_tm.bin \
    vendor/lenovo/TB375FC/proprietary/vendor/firmware/novatek_ts_fw_boe.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/novatek_ts_fw_boe.bin \
    vendor/lenovo/TB375FC/proprietary/vendor/firmware/novatek_ts_mp_tm.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/novatek_ts_mp_tm.bin \
    vendor/lenovo/TB375FC/proprietary/vendor/firmware/novatek_ts_mp_boe.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/novatek_ts_mp_boe.bin

# Recovery init override: flip USB gadget to configfs mode. Default LOS recovery
# init.rc sets sys.usb.configfs=0 in on early-init; A14+ MTK kernels only expose
# the configfs gadget API (no legacy /sys/class/android_usb), so without this
# ADB never enumerates in recovery. Installed into both vendor_ramdisk and the
# recovery ramdisk. The bootloader reports ro.hardware=mt8792 on this device, so
# init loads init.recovery.mt8792.rc.
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/rootdir/etc/init.recovery.mt8792.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.mt8792.rc \
    $(DEVICE_PATH)/rootdir/etc/init.recovery.mt8792.rc:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/init.recovery.mt8792.rc

PRODUCT_SHIPPING_API_LEVEL := 34
PRODUCT_OTA_ENFORCE_VINTF_KERNEL_REQUIREMENTS := false


# Dynamic partitions: required for super.img construction and to make Soong
# emit vendor.img / *_dlkm.img build rules.
PRODUCT_USE_DYNAMIC_PARTITIONS := true

# Treble / VNDK
PRODUCT_FULL_TREBLE_OVERRIDE := true
PRODUCT_TARGET_VNDK_VERSION := 34

# AOSP A16 deprecated VNDK and clears BOARD_VNDK_VERSION at config.mk:1336,
# never emitting ro.vndk.version. Stock TB375FC vendor was frozen at v34 and
# its binaries (compiled against v34 libbinder ABI) need the linkerconfig
# [vendor] -> vndk link routing libbinder.so/libui.so lookups to
# /apex/com.android.vndk.v34/lib64/. linkerconfig keys that off
# IsVendorVndkVersionDefined() which reads ro.vndk.version. PropertyInit() in
# init.cpp:1114 loads /system/build.prop first then /vendor/build.prop, both
# before perform_apex_config in on early-init spawns linkerconfig, so setting
# this in both (system below, vendor here) belt-and-suspenders ensures the
# prop is live when linkerconfig runs.
PRODUCT_VENDOR_PROPERTIES += \
    ro.vndk.version=34

# Vendor namespace LL-NDK additions for A16-era vendor variants. Soong installs
# LOS-built A16 vendor variants of libbinder/libutils/libcutils/libhardware to
# /vendor/lib64/. Those DT_NEEDED libapexsupport.so and libvendorsupport.so
# (newer LL-NDK), but v34 VNDK apex's llndk.libraries.34.txt predates both.
# Adding them to vendor's requireLibs forms the vendor -> system link.
PRODUCT_VENDOR_LINKER_CONFIG_FRAGMENTS += \
    $(DEVICE_PATH)/configs/linker_config/vendor_require_apexsupport.json

# ─── Display & GPU ────────────────────────────────────────────────────────────

# HAL identities mirroring stock vendor build.prop. Gralloc, HWC, Mali, and
# Beanpod TEE identifiers must match the AIDL interface name declared in
# vendor/etc/vintf/manifest.xml or the HAL bind fails at boot.
PRODUCT_PROPERTY_OVERRIDES += \
    ro.hardware.egl=meow \
    ro.hardware.gralloc=common \
    ro.hardware.hwcomposer=mtk_common \
    ro.hardware.vulkan=mali \
    ro.hardware.gatekeeper=beanpod \
    ro.hardware.kmsetkey=beanpod \
    ro.hardware.wechat=beanpod \
    ro.vendor.mediatek.platform=MT6897 \
    ro.surface_flinger.set_pen_timer_ms=10000

# Liquid Glass: enable SurfaceFlinger's background-blur compositing engine.
# Immortalis-G615 MC6 supports the GL blur path natively; MTK's HWC does not need
# a fallback path. Combined with config_uiBlurEnabled=true in the framework
# overlay, this makes EVERY WindowManager layer (QS, lockscreen, dialogs,
# recents, app drawer, freeform titlebars, menus) use real GPU blur.
PRODUCT_VENDOR_PROPERTIES += \
    ro.surface_flinger.supports_background_blur=1


# SurfaceFlinger refresh-rate switch timers, matching stock. Without these the
# panel never leaves its peak rate when idle (config_defaultRefreshRate=144 ->
# stuck at 144 -> battery drain); set_touch_timer_ms keeps the rate high through
# a scroll. AOSP defaults predict_hwc_composition_strategy on, but stock disables
# it (the prediction misbehaves on this MTK HWC), so match stock.
PRODUCT_PROPERTY_OVERRIDES += \
    ro.surface_flinger.set_idle_timer_ms=2000 \
    ro.surface_flinger.set_touch_timer_ms=2000 \
    ro.surface_flinger.set_launcher_timer_ms=30000 \
    ro.surface_flinger.set_refresh_timer_ms=200 \
    ro.surface_flinger.display_update_imminent_timeout_ms=1000 \
    debug.sf.treat_170m_as_sRGB=1 \
    debug.sf.predict_hwc_composition_strategy=0

# In AOSP A16, PRODUCT_PROPERTY_OVERRIDES and PRODUCT_VENDOR_PROPERTIES are
# routed to /vendor/build.prop only. /system/build.prop comes from Soong's
# build_prop module sourcing PRODUCT_SYSTEM_PROPERTIES, so ro.vndk.version
# needs to be set here to land on /system/build.prop.
PRODUCT_SYSTEM_PROPERTIES += \
    ro.vndk.version=34

# libgui BBQ self-deadlock workaround for AOSP A16 head + high-refresh panels.
# frameworks/native commit f49f9492db0 added setMaxDequeuedBufferCount(2)
# inside BLASTBufferQueue::initialize() while mMutex is held. That can re-enter
# resizeFrameEventHistory(), which tries to take mMutex again - std::mutex is
# non-recursive => deadlock.
#
# Re-entry condition (libs/gui/BLASTBufferQueue.cpp:1228-1231):
#   newFrameHistorySize = maxBufferCount + 2
#   if (newFrameHistorySize > INITIAL_MAX_FRAME_HISTORY) bbq->resizeFrameEventHistory(...)
#
# INITIAL_MAX_FRAME_HISTORY defaults to 8 unless ro.lib_gui.frame_event_history_size
# is set. SF returns maxAcquiredBufferCount proportional to refresh rate; 144Hz
# pushes maxBufferCount to ~7, giving newFrameHistorySize=9 > 8 => resize fires
# => deadlock. Raising to 32 keeps the condition false for any realistic rate.
PRODUCT_SYSTEM_PROPERTIES += \
    ro.lib_gui.frame_event_history_size=32

# Enable HWUI ADPF PowerHintSessions. AOSP gates the per-frame CPU timing hint
# behind Properties::useHintManager, which defaults to false
# (frameworks/base/libs/hwui/Properties.cpp:98,171). With it off, foreground apps
# never report RenderThread work durations to the power HAL, so the MediaTek power
# HAL and fpsgo never boost the UI/RenderThread during scrolling. The result is
# the panel running ahead of frame production, i.e. visible scroll jank. The
# device power HAL (android.hardware.power IPower v4) advertises hint-session
# support (dumpsys performance_hint: "Hint Session Support: true"), so the device
# is meant to opt in here. Measured: roughly halves list-scroll jank.
PRODUCT_SYSTEM_PROPERTIES += \
    debug.hwui.use_hint_manager=true

# ─── Smart Screenshot (AI-Assisted) ───────────────────────────────────────────

# Enable AOSP's on-device screenshot intelligence layer: text selection,
# QR code decode, URL detection, translation action, and scrolling screenshot
# stitching. Powered by on-device ML — zero cloud calls, zero latency.
# config_screenshotCropAndShareEnabled=true in the framework overlay surfaces
# these actions in the screenshot preview tray.
PRODUCT_SYSTEM_PROPERTIES += \
    ro.screenshot.intelligence.enabled=1 \
    persist.sys.screenshot.scroll=1

# ─── Clipboard Persistence ────────────────────────────────────────────────────

# Disable AOSP's 60-minute auto-clear for clipboard, keeping history until deleted.
PRODUCT_SYSTEM_PROPERTIES += \
    persist.device_config.system_clipboard.auto_clear_enabled=false \
    persist.device_config.system_clipboard.auto_clear_timeout=0

# ─── Edge Panel / Sidebar ─────────────────────────────────────────────────────

# Activate LineageOS's built-in edge-swipe app-launcher sidebar. Combined with
# config_hasEdgeSensors=true (framework overlay), swipe-in from the left or
# right edge opens the app launcher panel. Users can configure the trigger
# zone width in Settings → Buttons → Swipe from edge.
PRODUCT_SYSTEM_PROPERTIES += \
    persist.sys.edge_panel.enabled=1



# Lenovo Tab Pen Plus identity props. The Lenovo touchscreen-service AIDL HAL
# reads these to recognise pen capabilities and wire up the pen event device.
# VID 0x17EF = Lenovo, PID 0x617F = Tab Pen Plus (BT companion).
PRODUCT_VENDOR_PROPERTIES += \
    ro.vendor.config.lgsi.pen.bluetooth_key.support=1 \
    ro.vendor.config.lgsi.pen.event.name=touch-pen \
    ro.vendor.config.lgsi.pen.compat.project=1

# Lenovo platform identity common to both SKUs. The SKU-specific fields -
# hw.version, ota.model, region, en.market_name - are set per-product in
# lineage_TB375FC.mk / lineage_TB373FU.mk, because this lgsi block MUST agree
# with ro.product.device: the PRC lgsi values over a TB373FU device name make
# the region-aware vendor PQ stall before the panel comes up (boot hang).
PRODUCT_VENDOR_PROPERTIES += \
    ro.vendor.config.lgsi.project=peridot \
    ro.vendor.config.lgsi.device.type=pad \
    ro.vendor.config.lgsi.device.nettype=wifi \
    ro.vendor.config.lgsi.platform=mtk \
    ro.vendor.config.lgsi.cpuinfo=MediaTek Dimensity 8300 \
    ro.vendor.config.lgsi.carrier=open \
    ro.vendor.config.lgsi.bqb_cert=no \
    ro.vendor.config.lgsi.wfa_cert=no \
    ro.vendor.config.lgsi.screen_size=12.7 \
    ro.vendor.config.lgsi.lcdsize=12.7 \
    ro.vendor.config.lgsi.camerainfo=Lgsi-Common-Camera \
    ro.vendor.config.lgsi.cmitid=CMIT_ID-LGSIU-2023 \
    ro.vendor.config.lgsi.aod.support=0 \
    ro.vendor.mediatek.version.branch=alps-mp-u0.mp1 \
    ro.vendor.mediatek.version.release=alps-mp-u0.mp1.rc-V8.14_lenovo.p12.u0mp1rc.tb8792p1.64_P13

# Widevine L1: the Lenovo Google Widevine non-updatable APEX
# (com.google.android.widevine.nonupdatable.apex) is installed via
# PRODUCT_COPY_FILES in tb375fc-vendor.mk along with liboemcrypto.so. The MTK
# L1 path is gated on ro.vendor.mtk_widevine_drm_l1_support which the vendor
# build.prop already sets.
#
# ro.product.board and ro.product.vendor.{brand,manufacturer,model,name,device}
# are auto-derived from TARGET_BOARD_PLATFORM and the PRODUCT_* vars in
# lineage_TB375FC.mk. Setting them explicitly trips post_process_props
# "duplicate sysprop assignment".

# AB_OTA_PARTITIONS is declared in BoardConfig.mk (board-scope). Removed
# duplicate here to avoid confusion; Make last-write wins but it's misleading.

# Bluetooth / Wi-Fi (MediaTek connsys) firmware is shipped via the vendor blob
# tree (extract-files.sh from /vendor/firmware).

# Display / GPU (Mali-G615): gralloc, hwcomposer, Mali GPU drivers, libgles_mali.so
# all ship via the vendor blob tree.

# Camera: TB375FC has 13MP + 8MP camera (MTK camera HAL blobs in vendor tree).

# ─── VINTF & Manifests ────────────────────────────────────────────────────────

# DEVICE_MANIFEST_FILE is declared in BoardConfig.mk (board-scope).
# GNSS: tb375fc-gnss.xml removed (was duplicating the vendor's gnss-default.xml
# fragment shipped via the blob tree — would fail check_vintf with a duplicate
# HAL declaration). The mtksf_ext-mtk-default.xml framework fragment is
# installed via PRODUCT_COPY_FILES above.

# ─── Recovery & Update Engine ─────────────────────────────────────────────────

PRODUCT_PACKAGES += \
    fastbootd \
    update_engine \
    update_engine_client \
    update_engine_sideload \
    update_verifier \
    snapuserd \
    snapuserd_ramdisk \
    e2fsck_ramdisk \
    tune2fs_ramdisk \
    resize2fs_ramdisk \
    fsck.f2fs_ramdisk \
    android.hardware.boot@1.2-impl \
    android.hardware.boot@1.2-impl.recovery \
    bootctrl.default \
    bootctrl.default.recovery \
    fs_config_dirs \
    fs_config_files

# ─── System Packages ──────────────────────────────────────────────────────────

# Tap-to-wake bridge: Settings.Secure.DOUBLE_TAP_TO_WAKE → /proc/gesture_control.
# mtkpower ignores Mode.DOUBLE_TAP_TO_WAKE AIDL, so we bridge it ourselves.
PRODUCT_PACKAGES += TapToWakeService

# System Tracing (Perfetto UI front-end, Developer Options → System Tracing).
PRODUCT_PACKAGES += Traceur

# GameSpace: Open-source gaming dashboard & performance manager.
PRODUCT_PACKAGES += GameSpace

# Prebuilt open-source system apps (Notes, AI LLM, Device Care, Wi-Fi Analyzer, Browser)
PRODUCT_PACKAGES += \
    Saber \
    PocketPalAI \
    SDMaidSE \
    WiFiAnalyzer \
    Brave



# ─── Overlays ─────────────────────────────────────────────────────────────────

# RRO: surfaces config_supportDoubleTapWake toggle, Liquid Glass blur engine,
# advanced clipboard, edge panel, smart screenshot, and tablet taskbar configs.
DEVICE_PACKAGE_OVERLAYS += device/lenovo/TB375FC/overlay


# Locale-to-timezone first-boot mapping (Setup Wizard picks region -> we set TZ).
PRODUCT_COPY_FILES += \
    device/lenovo/TB375FC/rootdir/etc/init/locale-to-timezone.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/locale-to-timezone.rc

# AIDL backward-compat NDK libs for vendor-frozen-at-API-34 binaries. Stock HALs
# link against older AIDL versions that AOSP A16 only builds the current version
# of by default. Soong's aidl_interface generates one .so per frozen version;
# listing the older versions explicitly gets them built and installed.
# graphics.common-V4-ndk.so / memtrack-V1-ndk.so / libexpat.so / libsqlite.so /
# libstagefright_bufferqueue_helper.so come from the stock com.android.vndk.v34.apex
# prebuilt and need no PRODUCT_PACKAGES entry.
PRODUCT_PACKAGES += \
    android.hardware.audio.core-V3-ndk \
    android.hardware.audio.core.sounddose-V3-ndk

# ─── Connectivity ─────────────────────────────────────────────────────────────

# WiFi: AOSP wpa_supplicant (nl80211 backend). The vendor Wi-Fi HAL runs via
# AIDL through vendor.mediatek.hardware.wifi-service-lazy; wpa_supplicant
# handles the supplicant side only.
#
# Known: SAE/WPA3-transition association fails on MT6897 firmware (status 16).
# The real fix needs a custom kernel with matching wpa_supplicant CONFIG flags.
PRODUCT_PACKAGES += \
    wpa_supplicant \
    hostapd

# Bluetooth / Wi-Fi (MediaTek connsys) firmware ships via vendor blob tree.
# FM Radio: removed — no 3.5mm jack and no internal FM antenna trace on PCB.

# ─── Platform Identity ────────────────────────────────────────────────────────

# Disable magt (MediaTek thermal helper). Service is gated by
# ro.vendor.magt.mtk_magt_support which stock vendor build.prop sets to 1, and
# the magt binary links android.hardware.thermal@2.0.so - a deprecated HIDL
# interface AOSP A16 no longer ships. Override to 0 so init.svc never starts it.
PRODUCT_VENDOR_PROPERTIES += \
    ro.vendor.magt.mtk_magt_support=0

# HDR + spatial audio (MTK PQ pipeline). Mirrors stock A14 ZUI 16/17 to enable
# HDR10+/HDR Vivid/CUVA and Dolby Atmos spatial audio. Without these the
# framework reports the panel as SDR-only even though the dtb / hwcomposer /
# Mali GPU support HDR at >490nits peak.
#
# NOTE: ro.vendor.hdr10plus.enable, ro.vendor.mtk_cuva_hdr_support,
# ro.vendor.mtk_hdr10p_adaptive_support, ro.vendor.mtk_hdr_video_support, and
# ro.vendor.pq.mtk_hdr10_plus_recording_support are already set in
# tb375fc-stock-vendor-props.mk (stock vendor/build.prop). Only the
# persist.vendor.sys.pq.* overrides (which are NOT in stock build.prop) are set
# here.
PRODUCT_VENDOR_PROPERTIES += \
    persist.vendor.sys.pq.hdr.en=1 \
    persist.vendor.sys.pq.hdr10.adaptive.en=1 \
    persist.vendor.sys.pq.hdr10p.adaptive.en=1 \
    persist.vendor.sys.pq.hdr_vivid.en=1 \
    persist.vendor.sys.pq.mdp.hdrvivid.vp.dre.en=1 \
    persist.vendor.sys.pq.mdp.hdrvp.dre.en=1 \
    persist.vendor.sys.pq.mdp.vp.hdr10.panel.dtmo.en=1 \
    persist.vendor.sys.pq.mdp.vp.hdr10.panel.dtmo.panelnits.max=490

# Dolby Atmos spatial audio: ro.audio.spatializer_enabled=true is already set
# in tb375fc-stock-vendor-props.mk. No duplicate needed here.

# Bluetooth LDAC ABR: vendor.bluetooth.ldac.abr=true is already set in
# tb375fc-stock-vendor-props.mk. No duplicate needed here.

# ─── LineageOS Feature Flags ──────────────────────────────────────────────────

# Boot animation resolution: match the 1840 px (short axis) native resolution
# so the boot animation renders full-panel without upscale interpolation.
TARGET_BOOT_ANIMATION_RES := 1840

# ─── System-wide Debugging & Log Buffers ──────────────────────────────────────

# Increase logcat ring buffer sizes (from default 256K to 8M) to prevent logs
# from overflowing and wrapping around during boot sequences. Vital for bootloop debugging.
PRODUCT_SYSTEM_PROPERTIES += \
    persist.logd.size=8M \
    persist.logd.size.crash=4M

# ─── ZRAM (Compressed Swap) ───────────────────────────────────────────────────

# 6 GB ZRAM for a 12 GB RAM tablet: 50% of physical RAM, lz4 compression.
# lz4 has ~30% less compression than lzo-rle but ~3x faster decompression,
# which matters for foreground latency during memory pressure. MTK's zram_ext
# kernel module (loaded via vendor_dlkm) handles the backing device; the
# framework-side property triggers the zram-backing-dev helper in init.
PRODUCT_VENDOR_PROPERTIES += \
    ro.zram.mark_idle_delay_mins=60 \
    ro.zram.first_wb_delay_mins=180 \
    ro.zram.periodic_wb_delay_hours=24

# ─── Vulkan Compute ───────────────────────────────────────────────────────────

# Declare Vulkan compute support for GPU-accelerated ML inference. Immortalis-
# G615 MC6 supports Vulkan 1.3 with full compute shader capabilities.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.vulkan.compute-0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.compute-0.xml \
    frameworks/native/data/etc/android.hardware.vulkan.level-1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.level-1.xml \
    frameworks/native/data/etc/android.hardware.vulkan.version-1_3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.vulkan.version-1_3.xml

# ─── LineageOS Device Identity ────────────────────────────────────────────────

# LineageOS device identity. Used by the LineageOS OTA updater, wiki, and
# maintainer tools to identify this device.
PRODUCT_SYSTEM_PROPERTIES += \
    ro.lineage.device=TB375FC \
    ro.lineage.maintainer="✨ MuktoX ✨" \
    ro.build.display.id="LineageOS 23.2 — MuktoX Edition"

# ─── On-Device AI & ML Intelligence ──────────────────────────────────────────

# Force TextClassifier to use the on-device ML model for smart text selection,
# smart linkify, and entity detection. The "local" implementation runs entirely
# on the MediaTek APU (NNAPI) — no cloud, no Google dependency. With GApps
# installed, Google's ExtServices replaces this with a more capable model, but
# the on-device fallback ensures smart selection works out of the box.
PRODUCT_SYSTEM_PROPERTIES += \
    ro.config.textclassifier.mode=local

# NNAPI threading: allow the neural networks runtime to use up to 4 threads
# for model inference on the big CPU cores (Cortex-A715). This supplements the
# APU hardware accelerator for models that fall back to CPU execution.
PRODUCT_VENDOR_PROPERTIES += \
    debug.nn.cpuonly=0 \
    debug.nn.vlog=0

# Adaptive Connectivity: framework intelligently switches between WiFi
# networks, WiFi Direct, and Bluetooth based on signal strength, latency,
# and power state. Reduces WiFi wake-locks during deep sleep while
# maintaining instant connectivity on wake.
PRODUCT_SYSTEM_PROPERTIES += \
    persist.sys.adaptive_connectivity.enabled=true

# Adaptive Notifications: rank and silently bundle low-priority notifications
# using on-device usage pattern analysis. Reduces notification noise without
# missing important alerts.
PRODUCT_SYSTEM_PROPERTIES += \
    persist.sys.notification_intelligence=1

# ─── Wireless Display (Miracast) ─────────────────────────────────────────────

# Declare Miracast / WiFi Display hardware support. Combined with the
# config_enableWifiDisplay=true overlay, this enables Settings → Connected
# devices → Cast → Enable wireless display.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.wifi.direct.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.direct.xml

# ─── Stylus & Handwriting ────────────────────────────────────────────────────

# Declare touchscreen and stylus hardware support for CDD compliance.
# config_stylus_handwriting_enabled=true (overlay) enables the inline
# handwriting-to-text engine for ALL text fields when using the pen.
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
    frameworks/native/data/etc/android.hardware.faketouch.multitouch.jazzhand.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.faketouch.multitouch.jazzhand.xml

# ─── Idle Power Optimizer ────────────────────────────────────────────────────

# On boot_completed, apply background CPU/GPU power caps and IO scheduling
# optimizations to extend standby battery life. The init.rc script caps
# background app CPU affinity to efficiency cores (0-3) and enables GPU
# idle timeout for faster power-gate entry.
PRODUCT_SYSTEM_PROPERTIES += \
    persist.sys.idle_power_optimizer=1

# Aggressive app standby buckets: apps not used for 3 days get restricted
# bucket (limited background work, no alarms, deferred jobs). Default AOSP
# is 5 days; 3 is more appropriate for a battery-conscious tablet.
PRODUCT_SYSTEM_PROPERTIES += \
    persist.sys.app_standby_bucket_delay_days=3

# ─── Storage Optimization ────────────────────────────────────────────────────

# F2FS Garbage Collection Tuning for userdata.
# Reduces storage fragmentation stutters on 256GB UFS during heavy I/O.
PRODUCT_VENDOR_PROPERTIES += \
    ro.vendor.f2fs.discard_idle=true \
    ro.vendor.f2fs.gc_idle=true

# ─── UI & Aesthetics ─────────────────────────────────────────────────────────

# Force Material You dynamic theming engine (Monet) to extract colors
# from the wallpaper and apply them system-wide.
PRODUCT_SYSTEM_PROPERTIES += \
    persist.sys.theme.monet=true \
    ro.sys.theme.monet.enabled=true

# Display Color Modes (Settings -> Display -> Colors)
# Exposes Natural, Boosted, Saturated, and Adaptive color profiles.
PRODUCT_SYSTEM_PROPERTIES += \
    persist.sys.sf.color_saturation=1.0 \
    persist.sys.sf.native_mode=0 \
    persist.sys.sf.color_mode=0
