#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/lenovo/TB375FC

# MT6897 common trees from mt6897-devs/lineage-23.2:
# mssi.mk (RRO for telephony/wifi config), mediatek-frameworks.mk (adds
# mediatek-common to PRODUCT_BOOT_JARS), compat.mk (telephony-common-stub
# LineageOS compat shim). The Soong namespace addition lets platform-bootclasspath
# resolve mediatek-common.
PRODUCT_SOONG_NAMESPACES += hardware/mediatek

# The official hardware/mediatek tree builds the memtrack/thermal/vibrator HALs
# and the perf/power client libs from source. TB375FC/TB373FU ship all of these
# as prebuilt vendor blobs, so opt out of the source builds (otherwise the source
# module and the prebuilt collide on the vendor partition). These flags are read
# by select() in hardware/mediatek/{aidl/*,libmtkperf_client}/Android.bp.
$(call soong_config_set,mediatek_hardware,use_prebuilt_memtrack,true)
$(call soong_config_set,mediatek_hardware,use_prebuilt_thermal,true)
$(call soong_config_set,mediatek_hardware,use_prebuilt_vibrator,true)
$(call soong_config_set,mediatek_hardware,use_prebuilt_perf,true)

$(call inherit-product, hardware/mediatek/overlay/mssi.mk)
$(call inherit-product, hardware/mediatek/frameworks/mediatek-frameworks.mk)
$(call inherit-product, hardware/lineage/compat/frameworks/compat.mk)

# mediatek-frameworks.mk (inherited above) adds `mediatek-common` to
# PRODUCT_BOOT_JARS, which Soong resolves to the LOS-source java_library at
# hardware/mediatek/frameworks/common/Android.bp -- a 1712-byte dex stub with
# no real classes. Stock Lenovo MTK apps (GeofenceService, MtkSettingsProvider,
# callrecorder etc.) ClassNotFound-crash at runtime because the real
# com.mediatek.common.* classes live in the 88 KB proprietary jar at
# /system_ext/framework/mediatek-common.jar, which isn't on BOOTCLASSPATH.
#
# Fix: a dex_import at device/lenovo/TB375FC/prebuilts/framework/Android.bp
# is declared with the SAME name (`mediatek-common`) as the LOS source and
# `prefer: true`. Soong's source-vs-prebuilt resolution picks the prebuilt;
# the LOS source becomes inactive (not built, not installed, not in boot
# classpath). PRODUCT_BOOT_JARS keeps referring to `mediatek-common` and now
# resolves to our 88 KB jar.
#
# (Kept in device tree because vendor/lenovo/TB375FC/Android.bp is auto-
# generated by gen_vendor_mk.py and would wipe a dex_import added there.)

# Enable Android's built-in freeform window manager for tablet multitasking.
# Apps launched via the taskbar (Launcher3 tablet UI) render in resizable,
# movable windows. Replaces the broken Smart Connect / Ready For desktop mode
# with LOS-native multitasking - no Lenovo vendor blobs needed.
#
# The property is read at boot by PackageManagerService.hasSystemFeature() to
# advertise FEATURE_FREEFORM_WINDOW_MANAGEMENT, and by WindowManager to allow
# freeform launch modes. Tablet form factor + this prop is what unlocks the
# "windowed apps on home screen" UX you see in modern Android tablet builds.
PRODUCT_PROPERTY_OVERRIDES += persist.wm.freeform_window_management=1

# Conditional Access System HAL (AIDL). Stock A16 PRC ships it. Used by digital-
# broadcast and a few streaming apps to request content protection keys. Most
# modern streaming uses Widevine (we have that), but adding CAS prevents
# potential edge-case binding failures for apps that bind ICas at startup.
# AOSP A16 packages CAS as a vendor APEX; the example binary itself is
# installable: false because it is built into the APEX. Reference the APEX
# (com.android.hardware.cas) so the binary + init.rc + vintf fragment ship
# together at /vendor/apex/com.android.hardware.cas.apex.
PRODUCT_PACKAGES += com.android.hardware.cas

# System Tracing (Perfetto UI front-end, Developer Options -> System Tracing).
# AOSP dev/QoL tool; stock ships it at /system/app/Traceur but LOS doesn't pull
# it in by default for this product. Quick-settings tile + bug-report capture.
PRODUCT_PACKAGES += Traceur

# ro.boot.hardware=mt8792 but DT compatible is mediatek,MT6897, so stock ships
# both fstab.mt6897 and fstab.mt8792 (identical). Mirror that to cover both
# resolutions of fstab.${ro.hardware}.
#
# All Lenovo init.rc + fstab prebuilt_etc modules are auto-declared in
# rootdir/Android.bp and listed in tb375fc-rootdir-packages.mk.
include $(DEVICE_PATH)/tb375fc-rootdir-packages.mk

# tb375fc-vendor-symlinks.mk is NOT included here; its rules reference
# $(TARGET_OUT_VENDOR) which is unset during product-config. It is included
# from Android.mk instead, which runs after envsetup.mk.

# 367 vendor properties from stock vendor/build.prop (build.prop is generated,
# not blobbed). Includes Mali EGL config table, surfaceflinger phase offsets,
# MTK HAL knobs, Lenovo init triggers. Required for libGLES_mali eglInitialize.
include $(DEVICE_PATH)/tb375fc-stock-vendor-props.mk

PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/rootdir/etc/fstab.mt6897:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/first_stage_ramdisk/fstab.mt6897 \
    $(DEVICE_PATH)/rootdir/etc/fstab.mt6897:$(TARGET_COPY_OUT_RECOVERY)/root/first_stage_ramdisk/fstab.mt6897 \
    $(DEVICE_PATH)/rootdir/etc/fstab.mt8792:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/first_stage_ramdisk/fstab.mt8792 \
    $(DEVICE_PATH)/rootdir/etc/fstab.mt8792:$(TARGET_COPY_OUT_RECOVERY)/root/first_stage_ramdisk/fstab.mt8792

# Novatek NT36532 touch IC firmware. In recovery /vendor never mounts, so
# the kernel firmware loader can't find these unless they're in vendor_ramdisk00
# at /vendor/firmware/. In normal boot the real /vendor mount masks the
# ramdisk copy. Cost: 4 x 240 KB.
PRODUCT_COPY_FILES += \
    vendor/lenovo/TB375FC/proprietary/vendor/firmware/novatek_ts_fw_tm.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/novatek_ts_fw_tm.bin \
    vendor/lenovo/TB375FC/proprietary/vendor/firmware/novatek_ts_fw_boe.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/novatek_ts_fw_boe.bin \
    vendor/lenovo/TB375FC/proprietary/vendor/firmware/novatek_ts_mp_tm.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/novatek_ts_mp_tm.bin \
    vendor/lenovo/TB375FC/proprietary/vendor/firmware/novatek_ts_mp_boe.bin:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/vendor/firmware/novatek_ts_mp_boe.bin

# Recovery init override: flip USB gadget to configfs mode. Default LOS recovery
# init.rc sets sys.usb.configfs=0 in on early-init; A14+ MTK kernels only expose
# the configfs gadget API (no legacy /sys/class/android_usb), so without this
# ADB never enumerates in recovery. Installed into both vendor_ramdisk and the
# recovery ramdisk. The bootloader reports ro.hardware=mt8792 on this device, so
# init loads init.recovery.mt8792.rc.
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/rootdir/etc/init.recovery.mt8792.rc:$(TARGET_COPY_OUT_RECOVERY)/root/init.recovery.mt8792.rc \
    $(DEVICE_PATH)/rootdir/etc/init.recovery.mt8792.rc:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/init.recovery.mt8792.rc

PRODUCT_SHIPPING_API_LEVEL := 34
PRODUCT_OTA_ENFORCE_VINTF_KERNEL_REQUIREMENTS := false


# Dynamic partitions: required for super.img construction and to make Soong
# emit vendor.img / *_dlkm.img build rules.
PRODUCT_USE_DYNAMIC_PARTITIONS := true

# Treble / VNDK
PRODUCT_FULL_TREBLE_OVERRIDE := true
PRODUCT_TARGET_VNDK_VERSION := 34

# AOSP A16 deprecated VNDK and clears BOARD_VNDK_VERSION at config.mk:1336,
# never emitting ro.vndk.version. Stock TB375FC vendor was frozen at v34 and
# its binaries (compiled against v34 libbinder ABI) need the linkerconfig
# [vendor] -> vndk link routing libbinder.so/libui.so lookups to
# /apex/com.android.vndk.v34/lib64/. linkerconfig keys that off
# IsVendorVndkVersionDefined() which reads ro.vndk.version. PropertyInit() in
# init.cpp:1114 loads /system/build.prop first then /vendor/build.prop, both
# before perform_apex_config in on early-init spawns linkerconfig, so setting
# this in both (system below, vendor here) belt-and-suspenders ensures the
# prop is live when linkerconfig runs.
PRODUCT_VENDOR_PROPERTIES += \
    ro.vndk.version=34

# Vendor namespace LL-NDK additions for A16-era vendor variants. Soong installs
# LOS-built A16 vendor variants of libbinder/libutils/libcutils/libhardware to
# /vendor/lib64/. Those DT_NEEDED libapexsupport.so and libvendorsupport.so
# (newer LL-NDK), but v34 VNDK apex's llndk.libraries.34.txt predates both.
# Adding them to vendor's requireLibs forms the vendor -> system link.
PRODUCT_VENDOR_LINKER_CONFIG_FRAGMENTS += \
    $(DEVICE_PATH)/configs/linker_config/vendor_require_apexsupport.json

# HAL identities mirroring stock vendor build.prop.
TARGET_USES_AOSP_FOR_AUDIO := false
TARGET_USES_QCOM_BSP := false

PRODUCT_PROPERTY_OVERRIDES += \
    ro.hardware.egl=meow \
    ro.hardware.gralloc=common \
    ro.hardware.hwcomposer=mtk_common \
    ro.hardware.vulkan=mali \
    ro.hardware.gatekeeper=beanpod \
    ro.hardware.kmsetkey=beanpod \
    ro.hardware.wechat=beanpod \
    ro.vendor.mediatek.platform=MT6897 \
    ro.surface_flinger.set_pen_timer_ms=10000

# SurfaceFlinger refresh-rate switch timers, matching stock. Without these the
# panel never leaves its peak rate when idle (config_defaultRefreshRate=144 ->
# stuck at 144 -> battery drain); set_touch_timer_ms keeps the rate high through
# a scroll. AOSP defaults predict_hwc_composition_strategy on, but stock disables
# it (the prediction misbehaves on this MTK HWC), so match stock.
PRODUCT_PROPERTY_OVERRIDES += \
    ro.surface_flinger.set_idle_timer_ms=10000 \
    ro.surface_flinger.set_touch_timer_ms=2000 \
    ro.surface_flinger.set_launcher_timer_ms=30000 \
    ro.surface_flinger.set_refresh_timer_ms=200 \
    ro.surface_flinger.display_update_imminent_timeout_ms=1000 \
    debug.sf.treat_170m_as_sRGB=1 \
    debug.sf.predict_hwc_composition_strategy=0 \
    debug.sf.disable_backpressure=1 \
    debug.sf.latch_unsignaled=1 \
    ro.surface_flinger.enable_frame_rate_override=true \
    ro.surface_flinger.use_content_detection_for_refresh_rate=true


# In AOSP A16, PRODUCT_PROPERTY_OVERRIDES and PRODUCT_VENDOR_PROPERTIES are
# routed to /vendor/build.prop only. /system/build.prop comes from Soong's
# build_prop module sourcing PRODUCT_SYSTEM_PROPERTIES, so ro.vndk.version
# needs to be set here to land on /system/build.prop.
PRODUCT_SYSTEM_PROPERTIES += \
    ro.vndk.version=34

# libgui BBQ self-deadlock workaround for AOSP A16 head + high-refresh panels.
# frameworks/native commit f49f9492db0 added setMaxDequeuedBufferCount(2)
# inside BLASTBufferQueue::initialize() while mMutex is held. That can re-enter
# resizeFrameEventHistory(), which tries to take mMutex again - std::mutex is
# non-recursive => deadlock.
#
# Re-entry condition (libs/gui/BLASTBufferQueue.cpp:1228-1231):
#   newFrameHistorySize = maxBufferCount + 2
#   if (newFrameHistorySize > INITIAL_MAX_FRAME_HISTORY) bbq->resizeFrameEventHistory(...)
#
# INITIAL_MAX_FRAME_HISTORY defaults to 8 unless ro.lib_gui.frame_event_history_size
# is set. SF returns maxAcquiredBufferCount proportional to refresh rate; 144Hz
# pushes maxBufferCount to ~7, giving newFrameHistorySize=9 > 8 => resize fires
# => deadlock. Raising to 32 keeps the condition false for any realistic rate.
PRODUCT_SYSTEM_PROPERTIES += \
    ro.lib_gui.frame_event_history_size=32

# Enable HWUI ADPF PowerHintSessions. AOSP gates the per-frame CPU timing hint
# behind Properties::useHintManager, which defaults to false
# (frameworks/base/libs/hwui/Properties.cpp:98,171). With it off, foreground apps
# never report RenderThread work durations to the power HAL, so the MediaTek power
# HAL and fpsgo never boost the UI/RenderThread during scrolling. The result is
# the panel running ahead of frame production, i.e. visible scroll jank. The
# device power HAL (android.hardware.power IPower v4) advertises hint-session
# support (dumpsys performance_hint: "Hint Session Support: true"), so the device
# is meant to opt in here. Measured: roughly halves list-scroll jank.
PRODUCT_SYSTEM_PROPERTIES += \
    debug.hwui.use_hint_manager=true

# Lenovo Tab Pen Plus identity props. The Lenovo touchscreen-service AIDL HAL
# reads these to recognise pen capabilities and wire up the pen event device.
# VID 0x17EF = Lenovo, PID 0x617F = Tab Pen Plus (BT companion).
PRODUCT_VENDOR_PROPERTIES += \
    ro.vendor.config.lgsi.pen.bluetooth_key.support=1 \
    ro.vendor.config.lgsi.pen.event.name=touch-pen \
    ro.vendor.config.lgsi.pen.compat.project=1

# Lenovo platform identity common to both SKUs. The SKU-specific fields -
# hw.version, ota.model, region, en.market_name - are set per-product in
# lineage_TB375FC.mk / lineage_TB373FU.mk, because this lgsi block MUST agree
# with ro.product.device: the PRC lgsi values over a TB373FU device name make
# the region-aware vendor PQ stall before the panel comes up (boot hang).
PRODUCT_VENDOR_PROPERTIES += \
    ro.vendor.config.lgsi.project=peridot \
    ro.vendor.config.lgsi.device.type=pad \
    ro.vendor.config.lgsi.device.nettype=wifi \
    ro.vendor.config.lgsi.platform=mtk \
    ro.vendor.config.lgsi.cpuinfo=MediaTek Dimensity 8300 \
    ro.vendor.config.lgsi.carrier=open \
    ro.vendor.config.lgsi.bqb_cert=no \
    ro.vendor.config.lgsi.wfa_cert=no \
    ro.vendor.config.lgsi.screen_size=12.7 \
    ro.vendor.config.lgsi.lcdsize=12.7 \
    ro.vendor.config.lgsi.camerainfo=Lgsi-Common-Camera \
    ro.vendor.config.lgsi.cmitid=CMIT_ID-LGSIU-2023 \
    ro.vendor.config.lgsi.aod.support=0 \
    ro.vendor.mediatek.version.branch=alps-mp-u0.mp1 \
    ro.vendor.mediatek.version.release=alps-mp-u0.mp1.rc-V8.14_lenovo.p12.u0mp1rc.tb8792p1.64_P13

# Widevine L1: the Lenovo Google Widevine non-updatable APEX
# (com.google.android.widevine.nonupdatable.apex) is installed via
# PRODUCT_COPY_FILES in tb375fc-vendor.mk along with liboemcrypto.so. The MTK
# L1 path is gated on ro.vendor.mtk_widevine_drm_l1_support which the vendor
# build.prop already sets.
#
# ro.product.board and ro.product.vendor.{brand,manufacturer,model,name,device}
# are auto-derived from TARGET_BOARD_PLATFORM and the PRODUCT_* vars in
# lineage_TB375FC.mk. Setting them explicitly trips post_process_props
# "duplicate sysprop assignment".

# A/B + dynamic partitions
AB_OTA_PARTITIONS += \
    boot \
    vendor_boot \
    init_boot \
    dtbo \
    odm \
    odm_dlkm \
    product \
    system \
    system_dlkm \
    system_ext \
    vbmeta \
    vbmeta_system \
    vbmeta_vendor \
    vendor \
    vendor_dlkm

# Bluetooth / Wi-Fi (MediaTek connsys) firmware is shipped via the vendor blob
# tree (extract-files.sh from /vendor/firmware).

# Display / GPU (Mali-G615): gralloc, hwcomposer, Mali GPU drivers, libgles_mali.so
# all ship via the vendor blob tree.

# Camera: TB375FC has 13MP + 8MP camera (MTK camera HAL blobs in vendor tree).

DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/manifest.xml

# Standard GNSS HAL declaration. The vendor manifest.xml is a PRODUCT_COPY of the stock
# blob and declares only the MTK HALs (audio/bt/pq/...); the stock ROM declared
# GPS: android.hardware.gnss/IGnss/default ships via the stock gnss-default.xml fragment
# (now correctly shipped through proprietary-files.txt as a copy-rule, so no separate
# fragment is needed). The earlier tb375fc-gnss.xml workaround was removed - it duplicated
# the GNSS HAL declaration and broke check_vintf.

# Recovery / fastbootd / sideload packages. Without fastbootd,
# `fastboot reboot fastboot`
# lands in a recovery that can't enter userspace fastboot mode. Without
# update_engine_sideload, LOS Recovery's "Apply update from ADB" can't consume
# the OTA payload. bootctrl + boot HAL are needed for slot switching from recovery.
PRODUCT_PACKAGES += \
    fastbootd \
    update_engine \
    update_engine_client \
    update_engine_sideload \
    update_verifier \
    snapuserd \
    snapuserd_ramdisk \
    e2fsck_ramdisk \
    tune2fs_ramdisk \
    resize2fs_ramdisk \
    fsck.f2fs_ramdisk \
    android.hardware.boot@1.2-impl \
    android.hardware.boot@1.2-impl.recovery \
    bootctrl.default \
    bootctrl.default.recovery \
    fs_config_dirs \
    fs_config_files

# Tap-to-wake bridge: Settings.Secure.DOUBLE_TAP_TO_WAKE -> /proc/gesture_control.
# mtkpower ignores Mode.DOUBLE_TAP_TO_WAKE AIDL, so we bridge it ourselves.
PRODUCT_PACKAGES += \
    TapToWakeService

# RRO turning on config_supportDoubleTapWake so AOSP Settings -> Display
# surfaces the toggle.
DEVICE_PACKAGE_OVERLAYS += device/lenovo/TB375FC/overlay

# Locale-to-timezone first-boot mapping (Setup Wizard picks region -> we set TZ).
PRODUCT_COPY_FILES += \
    device/lenovo/TB375FC/rootdir/etc/init/locale-to-timezone.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/locale-to-timezone.rc

# AIDL backward-compat NDK libs for vendor-frozen-at-API-34 binaries. Stock HALs
# link against older AIDL versions that AOSP A16 only builds the current version
# of by default. Soong's aidl_interface generates one .so per frozen version;
# listing the older versions explicitly gets them built and installed.
# graphics.common-V4-ndk.so / memtrack-V1-ndk.so / libexpat.so / libsqlite.so /
# libstagefright_bufferqueue_helper.so come from the stock com.android.vndk.v34.apex
# prebuilt and need no PRODUCT_PACKAGES entry.
PRODUCT_PACKAGES += \
    android.hardware.audio.core-V3-ndk \
    android.hardware.audio.core.sounddose-V3-ndk

# FM Radio support removed: device has no 3.5mm jack (needed for the standard
# headphone-wire antenna) and no internal FM antenna trace on the PCB, so the
# chip detects no stations on any frequency. The kernel module
# (fmradio_drv_connac2x) is also stripped (see tb375fc-kernel-modules.mk).

# WiFi: AOSP wpa_supplicant. Soong builds it out of external/wpa_supplicant_8
# with nl80211 driver support once BOARD_WPA_SUPPLICANT_DRIVER=NL80211 is set;
# this entry triggers install to /vendor/bin/hw/wpa_supplicant. The
# /vendor/etc/init/android.hardware.wifi.supplicant-service.rc ships via vendor
# blobs and points to this path.
#
# Known limitation: AOSP wpa_supplicant fails SAE/WPA3-transition association
# on this device's MT6897 firmware with status_code=16. WiFi can scan and see
# networks but won't connect to APs advertising SAE alongside PSK (most modern
# routers + iOS 16+ hotspots). The real fix needs either a custom kernel with
# a WLAN driver that doesn't depend on MTK vendor netlink commands, or
# rebuilding wpa_supplicant_8 with CONFIG_* flags matching MTK driver
# expectations.
PRODUCT_PACKAGES += \
    wpa_supplicant \
    hostapd

# WiFi-only telephony cleanup. Telephony APKs absent via three paths:
#   - lineage_TB375FC.mk inherits full_base.mk (was full_base_telephony.mk),
#     dropping Dialer/TeleService/TelephonyProvider/Telecom/MmsService/
#     SimAppDialog/CarrierDefaultApp/ImsServiceEntitlement.
#   - tb375fc-vendor.mk PRODUCT_PACKAGES line for CarrierConfig commented out.
#   - ImsService was never in PRODUCT_PACKAGES, just had an Android.bp entry.

# Display orientation: keep stock ORIENTATION_270. The Novatek NT36532 kernel
# driver applies an internal rotation transform based on the DT-configured
# panel mount orientation (270 deg), which only aligns with the display when
# SurfaceFlinger primary_display_orientation matches stock. Changing SF
# without retuning the kernel touch driver leaves InputReader delivering tap
# coordinates rotated 270 deg relative to the rendered UI. Default is portrait;
# rotate the tablet 90 deg for landscape.

# Disable magt (MediaTek thermal helper). Service is gated by
# ro.vendor.magt.mtk_magt_support which stock vendor build.prop sets to 1, and
# the magt binary links android.hardware.thermal@2.0.so - a deprecated HIDL
# interface AOSP A16 no longer ships. Override to 0 so init.svc never starts it.
PRODUCT_VENDOR_PROPERTIES += \
    ro.vendor.magt.mtk_magt_support=0

# HDR + spatial audio (MTK PQ pipeline). Mirrors stock A14 ZUI 16/17 to enable
# HDR10+/HDR Vivid/CUVA and Dolby Atmos spatial audio. Without these the
# framework reports the panel as SDR-only even though the dtb / hwcomposer /
# Mali GPU support HDR at >490nits peak. The recording flag enables the camera
# HAL's HDR10+ recording path (10-bit HEVC).
PRODUCT_VENDOR_PROPERTIES += \
    persist.vendor.sys.pq.hdr.en=1 \
    persist.vendor.sys.pq.hdr10.adaptive.en=1 \
    persist.vendor.sys.pq.hdr10p.adaptive.en=1 \
    persist.vendor.sys.pq.hdr_vivid.en=1 \
    persist.vendor.sys.pq.mdp.hdrvivid.vp.dre.en=1 \
    persist.vendor.sys.pq.mdp.hdrvp.dre.en=1 \
    persist.vendor.sys.pq.mdp.vp.hdr10.panel.dtmo.en=1 \
    persist.vendor.sys.pq.mdp.vp.hdr10.panel.dtmo.panelnits.max=490 \
    ro.vendor.hdr10plus.enable=1 \
    ro.vendor.mtk_cuva_hdr_support=1 \
    ro.vendor.mtk_hdr10p_adaptive_support=1 \
    ro.vendor.mtk_hdr_video_support=1 \
    ro.vendor.pq.mtk_hdr10_plus_recording_support=1

# Dolby Atmos spatial audio in AudioFlinger. Combined with dax-default.xml +
# libdlbvol.so + daxService apk, surfaces the Spatial Audio toggle in
# Settings -> Sound.
PRODUCT_PROPERTY_OVERRIDES += \
    ro.audio.spatializer_enabled=true

# Bluetooth LDAC Adaptive Bit Rate. With ABR on, LDAC adjusts bit rate based
# on link quality. The kernel BT driver (bt_drv_6897) and stack both support
# it; this prop unlocks it at framework / bluedroid level.
PRODUCT_VENDOR_PROPERTIES += \
    vendor.bluetooth.ldac.abr=true

# LineageOS feature toggles
TARGET_BOOT_ANIMATION_RES := 1840

# Face Unlock
ifeq ($(TARGET_FACE_UNLOCK_SUPPORTED),true)
PRODUCT_PACKAGES += \
    FaceUnlock

PRODUCT_SYSTEM_EXT_PROPERTIES += \
    ro.face.sense_service=true

PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.biometrics.face.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/android.hardware.biometrics.face.xml
endif

# Offline Backup (Seedvault)
PRODUCT_PACKAGES += \
    Seedvault \
    LocalContactsBackup \
    com.stevesoltys.backup_allowlist \
    com.stevesoltys.backup_default-permissions \
    com.stevesoltys.backup_privapp_allowlist

# One UI Flavour Packages (Native zero-root integration)
PRODUCT_PACKAGES += \
    FontOneUISansOverlay \
    FontSamsungOneOverlay \
    ClockFontSamsungOneOverlay \
    NavbarOneUiOverlay \
    NavbarSammyOverlay \
    IconShapeSquircleOverlay \
    IconPackSamAndroidOverlay \
    IconPackSamLauncherOverlay \
    IconPackSamSettingsOverlay \
    IconPackSamSystemUIOverlay \
    IconPackSamThemePickerOverlay


