#!/usr/bin/env python3
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate tb375fc-vendor.mk, Android.bp and proprietary-files.txt from
# the actual contents of vendor/lenovo/TB375FC/proprietary/.
#
# AOSP rules:
#   .apk files cannot live in PRODUCT_COPY_FILES (kati hard error in
#   build/make/core/Makefile:148). They must be declared as
#   android_app_import in Android.bp.
#
#   .jar files in /framework/ should be declared as dex_import in
#   Android.bp, but PRODUCT_COPY_FILES is tolerated.
#
#   precompiled bytecode (.odex / .vdex / .art) under an app dir is
#   regenerated at boot by dex_preopt; ship the .apk and let it rebuild.
#
# Everything else (configs, .rc, .xml, .bin, .so, etc.) goes into the
# PRODUCT_COPY_FILES block in tb375fc-vendor.mk.

import os
import re

DEVICE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOS_ROOT = os.path.abspath(os.path.join(DEVICE_DIR, '..', '..', '..'))

# Sibling dev repository fallback
sibling_vendor = os.path.abspath(os.path.join(DEVICE_DIR, '..', 'android_vendor_lenovo_TB375FC'))
if os.path.isdir(sibling_vendor):
    VENDOR_DIR = sibling_vendor
else:
    VENDOR_DIR = os.path.join(LOS_ROOT, 'vendor', 'lenovo', 'TB375FC')
PROP_ROOT = os.path.join(VENDOR_DIR, 'proprietary')

PARTITION_MAP = {
    'vendor':     ('TARGET_COPY_OUT_VENDOR',     'vendor'),
    'product':    ('TARGET_COPY_OUT_PRODUCT',    'product_specific'),
    'system_ext': ('TARGET_COPY_OUT_SYSTEM_EXT', 'system_ext_specific'),
    'odm':        ('TARGET_COPY_OUT_ODM',        'device_specific'),
    'system':     ('TARGET_COPY_OUT_SYSTEM',     None),
}

# Drop these - they're regenerated at boot or by Soong dex_preopt.
SKIP_SUFFIXES = ('.odex', '.vdex', '.art')

# These basenames are generated by AOSP for every partition at build time.
# Copying them from proprietary/ either creates a ninja dependency cycle
# (install rule + generator rule both write the same target) or ships
# stale data that doesn't match our framework source revision.
#
# Protolog .pb/.json.gz files in particular: their group IDs are baked
# from frameworks/base annotations. Lenovo's stock-extracted versions
# lack groups added upstream after their build (e.g. WM_SHELL_WINDOW_DECORATION),
# so SystemUI crashes on every QS tile that touches the windowdecor path.
# Let AOSP/LOS regenerate them from our source tree instead.
SKIP_BASENAMES_PER_PARTITION = {
    'linker.config.pb',
    'fs_config_files',
    'fs_config_dirs',
    'group',
    'passwd',
    'public.libraries.txt',
    'linker.config.json',
    'plat_property_contexts',
    'core.protolog.pb',
    'wmshell.protolog.pb',
    'wmshell.protolog.json.gz',
    'launcher.quickstep.protolog.pb',
}

# Full relative paths to drop unconditionally. Use this for specific
# blobs that can't be shipped without other LOS-side changes.
SKIP_RELPATHS = set()

# APKs that need to be re-signed with the AOSP platform key. Stock Lenovo
# signs these with their own platform cert (matches their re-signed
# framework). On LineageOS the framework uses the AOSP platform key, so
# Lenovo-signed APKs that share android.uid.system or use signature-protected
# permissions fail PackageManagerService.reconcilePackages and crash
# system_server. certificate: "platform" makes Soong resign at build time.
#
# Add an APK here if scan_shareduserid_landmines() at the end of a run
# warns about it.
PLATFORM_CERT_APKS = {
    'daxService',
    'DolbyVisionService',
}


def partition_bp_attr(partition):
    flag = PARTITION_MAP[partition][1]
    if flag is None:
        return ''
    if flag == 'vendor':
        return '    vendor: true,\n'
    return '    {}: true,\n'.format(flag)


def make_module_name(rel):
    """Module name from path like product/app/LTHD/LTHD.apk -> LTHD."""
    base = os.path.basename(rel)
    name = re.sub(r'\.apk$', '', base)
    return name


def walk_proprietary():
    for root, dirs, files in os.walk(PROP_ROOT):
        dirs.sort()
        for f in sorted(files):
            full = os.path.join(root, f)
            if not os.path.isfile(full):
                continue
            rel = os.path.relpath(full, PROP_ROOT).replace(os.sep, '/')
            yield full, rel


def classify():
    apks = []      # list of (rel, partition, privileged, module_name)
    copies = []   # list of (partition, rest, rel)
    skipped = []
    # First pass: find APKs
    apk_paths = set()
    for full, rel in walk_proprietary():
        if rel.endswith('.apk'):
            apk_paths.add(rel)

    # Second pass: classify each file
    seen_names = set()
    for full, rel in walk_proprietary():
        parts = rel.split('/', 1)
        if len(parts) != 2:
            skipped.append(rel + ' (no partition prefix)')
            continue
        partition, rest = parts
        if partition not in PARTITION_MAP:
            skipped.append(rel + ' (unmapped partition: {})'.format(partition))
            continue

        st = os.lstat(full)
        if st.st_size == 0:
            skipped.append(rel + ' (0-byte)')
            continue

        # Skip preopt bytecode
        if rel.endswith(SKIP_SUFFIXES):
            skipped.append(rel + ' (preopt bytecode)')
            continue

        # Skip AOSP-generated files (would create ninja dep cycles)
        if os.path.basename(rel) in SKIP_BASENAMES_PER_PARTITION:
            skipped.append(rel + ' (AOSP-generated, dep cycle)')
            continue

        # Skip explicit deny-list (LOS-side patches needed first)
        if rel in SKIP_RELPATHS:
            skipped.append(rel + ' (in SKIP_RELPATHS)')
            continue

        # APK -> Android.bp (only for /app/, /priv-app/, /overlay/ paths).
        # Other .apk locations (e.g. fs-verity build manifest at
        # system_ext/etc/security/fsverity/BuildManifestSystemExt.apk) are
        # not real apps - they're container files in dedicated subtrees and
        # need to land at their exact source path. AOSP forbids them in
        # PRODUCT_COPY_FILES, so we drop them: stock fs-verity manifests
        # don't apply to LOS-rebuilt mainline modules anyway.
        if rel.endswith('.apk'):
            is_app = ('/app/' in rel or
                      '/priv-app/' in rel or
                      '/overlay/' in rel)
            if not is_app:
                skipped.append(rel + ' (.apk outside /app|/priv-app|/overlay)')
                continue
            privileged = '/priv-app/' in rel
            name = make_module_name(rel)
            if name in seen_names:
                name = '{}_{}'.format(partition, name)
            seen_names.add(name)
            apks.append((rel, partition, privileged, name))
            continue

        # Everything else -> PRODUCT_COPY_FILES
        copies.append((partition, rest, rel))

    return apks, copies, skipped


VENDOR_MK_HEADER = '''# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#
# Auto-generated by device/lenovo/TB375FC/tools/gen_vendor_mk.py.
# APKs live in Android.bp as android_app_import (AOSP forbids them in
# PRODUCT_COPY_FILES); everything else lands here. Regenerate after any
# proprietary/ change with:
#   python3 device/lenovo/TB375FC/tools/gen_vendor_mk.py

PRODUCT_SOONG_NAMESPACES += \\
    vendor/lenovo/TB375FC

'''

ANDROID_BP_HEADER = '''// SPDX-FileCopyrightText: The LineageOS Project
// SPDX-License-Identifier: Apache-2.0
//
// Auto-generated by device/lenovo/TB375FC/tools/gen_vendor_mk.py.
// One android_app_import entry per prebuilt APK in proprietary/.

soong_namespace {
}

'''

PROP_FILES_HEADER = '''# Proprietary files for TB375FC
# Auto-generated by device/lenovo/TB375FC/tools/gen_vendor_mk.py from the
# actual vendor/lenovo/TB375FC/proprietary/ tree. Every entry corresponds
# to a real file on disk; the build will not fail on a missing source.

'''


def write_vendor_mk(copies):
    mk_path = os.path.join(VENDOR_DIR, 'TB375FC-vendor.mk')
    with open(mk_path, 'w') as f:
        f.write(VENDOR_MK_HEADER)
        f.write('PRODUCT_COPY_FILES += \\\n')
        for i, (partition, rest, rel) in enumerate(sorted(copies, key=lambda x: x[2])):
            target_var = PARTITION_MAP[partition][0]
            src = 'vendor/lenovo/TB375FC/proprietary/{}'.format(rel)
            target = '$({})/{}'.format(target_var, rest)
            sep = ' \\' if i < len(copies) - 1 else ''
            f.write('    {}:{}{}\n'.format(src, target, sep))
    return mk_path


def write_android_bp(apks):
    bp_path = os.path.join(VENDOR_DIR, 'Android.bp')
    with open(bp_path, 'w') as f:
        f.write(ANDROID_BP_HEADER)
        for rel, partition, privileged, name in sorted(apks, key=lambda x: x[3]):
            f.write('android_app_import {\n')
            f.write('    name: "{}",\n'.format(name))
            f.write('    owner: "lenovo",\n')
            f.write('    apk: "proprietary/{}",\n'.format(rel))
            if name in PLATFORM_CERT_APKS:
                # Soong resigns with build/make/target/product/security/platform.*.
                # presigned + preprocessed conflict with certificate; omit both.
                # APKs are aligned upstream so zipalign + apksigner v2 run cleanly.
                f.write('    certificate: "platform",\n')
            else:
                f.write('    presigned: true,\n')
                # AOSP requires preprocessed: true for presigned apks with
                # targetSdkVersion >= 30 (signature v2; re-aligning invalidates
                # the signature). Every modern apk hits this.
                f.write('    preprocessed: true,\n')
            if privileged:
                f.write('    privileged: true,\n')
            f.write('    dex_preopt: {\n        enabled: false,\n    },\n')
            attr = partition_bp_attr(partition)
            if attr:
                f.write(attr)
            f.write('}\n\n')
    return bp_path


def scan_shareduserid_landmines(apks):
    """Warn about new APKs with sharedUserId that aren't in PLATFORM_CERT_APKS.

    Apps with sharedUserId="android.uid.system" must be platform-signed or
    PackageManagerService.reconcilePackages crashes system_server. This scan
    catches the case where a fresh extract-files brings in an unfamiliar APK
    that would silently brick the next boot.

    Requires aapt2; falls back to a silent no-op if aapt2 isn't available
    (e.g. when running the script before envsetup has populated out/host).
    """
    import subprocess
    aapt = os.path.join(LOS_ROOT, 'out', 'host', 'linux-x86', 'bin', 'aapt2')
    if not os.path.isfile(aapt):
        return []
    warnings = []
    for rel, _, _, name in apks:
        if name in PLATFORM_CERT_APKS:
            continue
        full = os.path.join(PROP_ROOT, rel)
        try:
            out = subprocess.run(
                [aapt, 'dump', 'xmltree', full, '--file', 'AndroidManifest.xml'],
                capture_output=True, text=True, timeout=10,
            ).stdout
        except (subprocess.SubprocessError, OSError):
            continue
        m = re.search(r'sharedUserId.*?="([^"]+)"', out)
        if not m:
            continue
        su = m.group(1)
        if su == 'android.uid.system':
            warnings.append((name, rel, su))
    return warnings


def write_prop_files(apks, copies):
    pf_paths = [
        os.path.join(DEVICE_DIR, 'proprietary-files.txt'),
        os.path.join(VENDOR_DIR, 'proprietary-files.txt'),
    ]
    rels = sorted([rel for rel, _, _, _ in apks] + [rel for _, _, rel in copies])
    for pf_path in pf_paths:
        with open(pf_path, 'w') as f:
            f.write(PROP_FILES_HEADER)
            for rel in rels:
                f.write('{}\n'.format(rel))
    return pf_paths


def need_packages_makefile(apks):
    """Add PRODUCT_PACKAGES entries so the build pulls in the APK modules."""
    if not apks:
        return
    mk_path = os.path.join(VENDOR_DIR, 'TB375FC-vendor.mk')
    lines = ['\nPRODUCT_PACKAGES += \\\n']
    names = sorted(name for _, _, _, name in apks)
    for i, n in enumerate(names):
        sep = ' \\' if i < len(names) - 1 else ''
        lines.append('    {}{}\n'.format(n, sep))
    with open(mk_path, 'a') as f:
        f.writelines(lines)


def main():
    apks, copies, skipped = classify()

    mk = write_vendor_mk(copies)
    print('Wrote {} ({} PRODUCT_COPY_FILES entries)'.format(mk, len(copies)))

    bp = write_android_bp(apks)
    print('Wrote {} ({} android_app_import entries)'.format(bp, len(apks)))

    need_packages_makefile(apks)
    print('Appended PRODUCT_PACKAGES with {} apk module names to {}'.format(len(apks), mk))

    pfs = write_prop_files(apks, copies)
    for pf in pfs:
        print('Wrote {} ({} entries)'.format(pf, len(apks) + len(copies)))

    if skipped:
        print('\nSkipped {} entries:'.format(len(skipped)))
        # Categorise
        cats = {}
        for s in skipped:
            reason = s.split('(')[-1].rstrip(')')
            cats.setdefault(reason, []).append(s)
        for reason, items in cats.items():
            print('  {}: {}'.format(reason, len(items)))

    landmines = scan_shareduserid_landmines(apks)
    if landmines:
        print('\nWARNING: APKs with sharedUserId="android.uid.system" not in')
        print('PLATFORM_CERT_APKS. These will crash system_server on boot.')
        print('Add to PLATFORM_CERT_APKS at the top of this script, or move')
        print('the APK out of proprietary/:')
        for name, rel, su in landmines:
            print('  {} ({}) -> sharedUserId={}'.format(name, rel, su))


if __name__ == '__main__':
    main()
